### ISSUE TITLE
RPI (A/B) Toolchain Compatibility

### ISSUE THREAD

**Issue by nickgal** [nerves-project/homebrew-nerves#1]
The packaged toolchain doesn't work when compiling NIFs etc.

Replacing the contents of my `/usr/local/opt/nerves-toolchain` with https://github.com/nerves-project/nerves-toolchain/releases/download/v0.4.0/nerves-toolchain-armv6-rpi-linux-gnueabi-Darwin-x86_64-v0.4.0.tar.xz as noted in the nerves-toolchain readme lets me compile for my RPI B.

Maybe we add another formula for the raspberry pi one toolchain?

**Comment by fhunleth** [comment]
Hi - I haven't been paying too close attention to the `homebrew-nerves` repo since I don't use it, but there are some challenges with this route as I understand it. One of these is that the system.tar.gz images start getting customized once you get into more advanced projects with Nerves. The whole Bakeware infrastructure that @ghitchens uses handles this. For basic Nerves use, it's fine and I've been trying to make the base system.tar.gz more generic, but there's only so far I can take it. I think that @kfatehi, you and the rest of the core Nerves team should chat about this level of integration with homebrew before we invest too much time in it. It may be a great direction to go, but it may lead to a lot of frustration if we don't do it right. Can we hash this out over Slack either this weekend or next depending on everyone's availability?

**Comment by kfatehi** [comment]
Hey @nickgal, that was my bad... I whipped up this repo very quickly just to see how the workflow felt (since @fhunleth had already done most of the work and we just needed a way to "install" everything on Mac)

Apparently I missed that there are different toolchain releases depending on the device target (rpi, bbb, rpi2). IIRC, at the time that I swiped the URL off the nerves-toolchain releases web page, this was not the case.

Yeah sure, I'll be on Slack.
